### ISSUE TITLE
'vagrant up' fails on basic-ubuntu

### ISSUE THREAD

**Issue by davisjam** [CamFlow/vagrant#6]
I tried to run the `basic-ubuntu` image. This uses a version of CamFlow that specifies a version of Linux that requires libelf-dev/libelf-devel/elfutils-libelf-devel, so 'vagrant up' errors out when trying to compile the kernel.

**Comment by davisjam** [comment]
I'm guessing this patch would work:

```
diff --git a/basic-ubuntu/Vagrantfile b/basic-ubuntu/Vagrantfile
index 27f34ed..2739b93 100644
--- a/basic-ubuntu/Vagrantfile
+++ b/basic-ubuntu/Vagrantfile
@@ -73,7 +73,7 @@ Vagrant.configure(2) do |config|
     sudo cp -f /vagrant/it /usr/bin/it
     sudo chmod 755 /usr/bin/it
     sudo apt-get -y install build-essential
-    sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev bc nano patch mosquitto
+    sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev bc nano patch mosquitto libelf-dev
     sudo apt-get -y install ncurses-dev libncurses5-dev
     sudo apt-get -y install bison flex
     git clone https://github.com/CamFlow/camflow-install.git
```

(I added `libelf-dev` to the end of the list).

Presumably other images also need to be updated.
I did not have trouble with the `rpm` image though.

I imagine this problem was introduced in v0.4.2 or some other recent release.

**Comment by davisjam** [comment]
@tfjmp Presumably fixed by a8ed7678ff4a1?

**Comment by tfjmp** [comment]
I think there is some issue with some static assertion left. That is a pain, as it as to do with gcc not deciding to inline some code, and it is kernel config dependent.

**Comment by tfjmp** [comment]
However, basic-fedora is working fine.

**Comment by tfjmp** [comment]
That has been fixed a while ago. I believe everything is working at the moment.

Also if my memory of twitter serves, congratulations are due ;).
