### ISSUE TITLE
Adding reboot into provisioning script?

### ISSUE THREAD

**Issue by dme26** [CamFlow/vagrant#8]
The instructions on http://camflow.org seem to unconditionally require rebooting the VM created by the Vagrant file, however it might be desirable to reboot at the bottom of the Vagrant provisioning script, unless there are common cases of pre-reboot additional configuration that might be useful.

**Comment by tfjmp** [comment]
I think that was causing issues in certain scenario (it used to be this way). Though I cannot remember what was the problem. I close it, but maybe worth investigating again.
